name: Windows

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'
    - '.github/workflows/linux-multiarch-build.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - 'assets/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'
    - '.github/workflows/ubuntu-build.yml'
    - '.github/workflows/macos-build.yml'
    - '.github/workflows/linux-multiarch-build.yml'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: ["x86", "x64"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: ${{ matrix.arch }} 

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Build sources, tests and make installer
      run: python3 build.py --arch=${{matrix.arch}} -Wall -Werror --make-installer
    
    - name: Install from installer
      run: .\\builder\\packaging\\dist\\kithare-0.0.1rc1-${{ matrix.arch }}.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /NOCANCEL
    
    - name: Run tests
      run: python3 build.py test --arch=${{matrix.arch}}
    
    # TODO: Test with installed kcr as well
    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        path: builder/packaging/dist/
